apiVersion: v1
kind: Service
metadata: 
  labels: 
    name: wpfrontend
  name: wpfrontend
spec: 
  ports:
    - port: 80 
      targetPort: wordpress 
  selector: 
    name: wordpress
  type: LoadBalancer