apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /OSE_wordpress
    server: storage.lab.example.com
  persistentVolumeReclaimPolicy: Recycle
